import type { Field } from "@/components/field-card"

export const mockFields: Field[] = [
  {
    id: "cancha-a",
    name: "Cancha A",
    type: "Fútbol 5 - Césped Sintético",
    status: "available",
    image: "/soccer-field-with-synthetic-grass-and-white-lines.jpg",
    nextReservation: undefined,
    price: 15000,
  },
  {
    id: "cancha-b",
    name: "Cancha B",
    type: "Fútbol 7 - Césped Natural",
    status: "occupied",
    image: "/natural-grass-soccer-field-with-green-turf.jpg",
    nextReservation: {
      time: "18:00",
      client: "Carlos Méndez",
    },
    price: 20000,
  },
  {
    id: "cancha-c",
    name: "Cancha C",
    type: "Fútbol 5 - Techada",
    status: "reserved",
    image: "/indoor-covered-soccer-field-with-roof-and-lights.jpg",
    nextReservation: {
      time: "16:30",
      client: "Equipo Los Tigres",
    },
    price: 18000,
  },
  {
    id: "cancha-d",
    name: "Cancha D",
    type: "Fútbol 11 - Profesional",
    status: "available",
    image: "/professional-soccer-field-with-stadium-lights.jpg",
    nextReservation: undefined,
    price: 35000,
  },
  {
    id: "cancha-e",
    name: "Cancha E",
    type: "Fútbol 5 - Césped Sintético",
    status: "reserved",
    image: "/small-soccer-field-with-blue-sky-and-synthetic-tur.jpg",
    nextReservation: {
      time: "15:00",
      client: "María González",
    },
    price: 15000,
  },
  {
    id: "cancha-f",
    name: "Cancha F",
    type: "Fútbol 7 - Techada",
    image: "/indoor-soccer-field-with-green-artificial-turf-and.jpg",
    status: "available",
    nextReservation: undefined,
    price: 22000,
  },
]

export const mockReservations = [
  {
    id: "1",
    time: "08:00 - 09:00",
    client: "Juan Pérez",
    status: "completed" as const,
    comments: "Pago confirmado",
  },
  {
    id: "2",
    time: "09:00 - 10:00",
    client: "Equipo Los Leones",
    status: "completed" as const,
    comments: "Reserva recurrente",
  },
  {
    id: "3",
    time: "10:00 - 11:00",
    client: "Ana Martínez",
    status: "occupied" as const,
    comments: "En progreso",
  },
  {
    id: "4",
    time: "11:00 - 12:00",
    client: "Club Deportivo",
    status: "reserved" as const,
    comments: "Torneo local",
  },
  {
    id: "5",
    time: "12:00 - 13:00",
    client: "Roberto Silva",
    status: "reserved" as const,
  },
  {
    id: "6",
    time: "13:00 - 14:00",
    client: "Equipo Juvenil",
    status: "cancelled" as const,
    comments: "Cancelado por lluvia",
  },
  {
    id: "7",
    time: "14:00 - 15:00",
    client: "Laura Rodríguez",
    status: "reserved" as const,
    comments: "Primera vez",
  },
  {
    id: "8",
    time: "15:00 - 16:00",
    client: "Grupo Amigos FC",
    status: "reserved" as const,
  },
]

export interface Reservation {
  id: string
  fieldId: string
  fieldName: string
  date: string
  startTime: string
  endTime: string
  clientName: string
  clientPhone: string
  clientEmail?: string
  price: number
  completed: boolean
  comments?: string
}

export const mockAllReservations: Reservation[] = [
  {
    id: "res-1",
    fieldId: "cancha-a",
    fieldName: "Cancha A",
    date: new Date().toISOString().split("T")[0],
    startTime: "08:00",
    endTime: "09:00",
    clientName: "Juan Pérez",
    clientPhone: "+54 11 1234-5678",
    clientEmail: "juan@ejemplo.com",
    price: 15000,
    completed: true,
    comments: "Pago en efectivo",
  },
  {
    id: "res-2",
    fieldId: "cancha-b",
    fieldName: "Cancha B",
    date: new Date().toISOString().split("T")[0],
    startTime: "09:00",
    endTime: "10:30",
    clientName: "Carlos Méndez",
    clientPhone: "+54 11 2345-6789",
    price: 30000,
    completed: false,
  },
  {
    id: "res-3",
    fieldId: "cancha-c",
    fieldName: "Cancha C",
    date: new Date().toISOString().split("T")[0],
    startTime: "10:00",
    endTime: "11:00",
    clientName: "Equipo Los Tigres",
    clientPhone: "+54 11 3456-7890",
    clientEmail: "tigres@equipo.com",
    price: 18000,
    completed: true,
    comments: "Reserva recurrente - todos los martes",
  },
  {
    id: "res-4",
    fieldId: "cancha-a",
    fieldName: "Cancha A",
    date: new Date().toISOString().split("T")[0],
    startTime: "11:00",
    endTime: "12:00",
    clientName: "Ana Martínez",
    clientPhone: "+54 11 4567-8901",
    price: 15000,
    completed: false,
  },
  {
    id: "res-5",
    fieldId: "cancha-d",
    fieldName: "Cancha D",
    date: new Date().toISOString().split("T")[0],
    startTime: "14:00",
    endTime: "16:00",
    clientName: "Club Deportivo Central",
    clientPhone: "+54 11 5678-9012",
    clientEmail: "central@club.com",
    price: 70000,
    completed: false,
    comments: "Torneo local - necesitan vestuarios",
  },
  {
    id: "res-6",
    fieldId: "cancha-e",
    fieldName: "Cancha E",
    date: new Date().toISOString().split("T")[0],
    startTime: "15:00",
    endTime: "16:00",
    clientName: "María González",
    clientPhone: "+54 11 6789-0123",
    price: 15000,
    completed: true,
  },
  {
    id: "res-7",
    fieldId: "cancha-c",
    fieldName: "Cancha C",
    date: new Date().toISOString().split("T")[0],
    startTime: "16:30",
    endTime: "17:30",
    clientName: "Roberto Silva",
    clientPhone: "+54 11 7890-1234",
    price: 18000,
    completed: false,
  },
  {
    id: "res-8",
    fieldId: "cancha-f",
    fieldName: "Cancha F",
    date: new Date().toISOString().split("T")[0],
    startTime: "18:00",
    endTime: "19:30",
    clientName: "Grupo Amigos FC",
    clientPhone: "+54 11 8901-2345",
    clientEmail: "amigos@fc.com",
    price: 33000,
    completed: false,
    comments: "Primera vez - enviar ubicación por WhatsApp",
  },
  {
    id: "res-9",
    fieldId: "cancha-b",
    fieldName: "Cancha B",
    date: new Date().toISOString().split("T")[0],
    startTime: "19:00",
    endTime: "20:00",
    clientName: "Laura Rodríguez",
    clientPhone: "+54 11 9012-3456",
    price: 20000,
    completed: true,
  },
  {
    id: "res-10",
    fieldId: "cancha-a",
    fieldName: "Cancha A",
    date: new Date().toISOString().split("T")[0],
    startTime: "20:00",
    endTime: "21:00",
    clientName: "Equipo Juvenil",
    clientPhone: "+54 11 0123-4567",
    price: 15000,
    completed: false,
  },
]
